# Generated by Django 5.0.3 on 2024-04-02 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0014_alter_consumer_id_alter_contact_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="consumer",
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="user",
        ),
        migrations.DeleteModel(
            name="Consumer",
        ),
        migrations.DeleteModel(
            name="Review",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
